### PR TITLE
fix(course selector): fixed ui of disproportional loading status on first tab load

### LINKED ISSUE #1119: First tab has very weird sized loading symbol on first page load of Course Selector

### PR DESCRIPTION
**Pull request by pikapiku**
- Modified the spinner design for course tab load to fit into the tab component.

### CODE REVIEW

File: frontend/src/components/Spinner/Spinner.tsx [hunk 1]
```diff
@@ -5,13 +5,25 @@ import S from './styles';
...
+  component?: string;
 };
 
-const Spinner = ({ text }: Props) => (
-  <S.Wrapper className="loading-spinner">
-    <Spin indicator={<LoadingOutlined style={{ fontSize: '2.5rem' }} spin />} />
-    <p>{text}</p>
-  </S.Wrapper>
-);
+const Spinner = ({ text, component = '' }: Props) => {
```
Comment (ollibowers) [inline frontend/src/components/Spinner/Spinner.tsx]: good idea, but maybe for reusability, we could instead make the `component` prop be `size`, that has a possible string type of `'small' | 'large'` (defaulting to large).

File: frontend/src/components/Spinner/Spinner.tsx [hunk 2]
```diff
@@ -5,13 +5,25 @@ import S from './styles';
...
+  // modify spinner css for course tab loads
+  if (component === 'course-tab') {
+    return (
+      <S.Wrapper className="loading-spinner" style={{ gap: '1px' }}>
```
Comment (ollibowers) [inline frontend/src/components/Spinner/Spinner.tsx]: and then you can make two wrapper styles for small or large, and have no on-element styling.
(orrrrr rewrite styled wrapper to be an antd Flex as we woed about last meeting :sob:)

**Review by ollibowers — CHANGES_REQUESTED** [review]

File: frontend/src/components/Spinner/Spinner.tsx (hunk 2 above)
Comment (ollibowers) [reply frontend/src/components/Spinner/Spinner.tsx]: alsoooooo, make small a flex row

File: frontend/src/components/Spinner/Spinner.tsx [hunk 3]
```diff
@@ -5,13 +5,30 @@ import S from './styles';
 
 type Props = {
   text: string;
+  size?: string;
```
Comment (ollibowers) [inline frontend/src/components/Spinner/Spinner.tsx]:
```suggestion
  size?: 'small' | 'large';
```
If we do something like this, then the intellisense will be able to tell you the options and we will get more typechecking capability.

File: frontend/src/components/Spinner/Spinner.tsx [hunk 4]
```diff
@@ -5,13 +5,30 @@ import S from './styles';
...
+  if (size === 'large') {
+    return (
+      <S.LargeWrapper className="loading-spinner">
+        <Spin indicator={<LoadingOutlined spin />} size="large" />
+        <p>{text}</p>
+      </S.LargeWrapper>
+    );
+  }
+
+  return null;
```
Comment (ollibowers) [inline frontend/src/components/Spinner/Spinner.tsx]: I think this is fine (and should never be reachable if we pass typecheck), but might lead to bugs that become hard to find. It might be better to just make the large condition the else condition, so we never have to deal with a backup return.

**Review by ollibowers — CHANGES_REQUESTED** [review]
some small last changes requested, otherwise this looks really good!

**Review by ollibowers — APPROVED** [review]
looks good to me! 
I can imagine there are a few more spots where we would need this, but we can address those as we notice them (which is much easier to do now)!
